-- MySQL Script generated by MySQL Workbench
-- Tue Sep 15 11:33:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trab` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `trab` ;

-- -----------------------------------------------------
-- Table `trab`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab`.`contato` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL DEFAULT NULL,
  `APELIDO` VARCHAR(45) NULL DEFAULT NULL,
  `OFICINA` VARCHAR(45) NULL DEFAULT NULL,
  `ENDERECO` VARCHAR(80) NULL DEFAULT NULL,
  `BAIRRO` VARCHAR(45) NULL DEFAULT NULL,
  `CIDADE` VARCHAR(45) NULL DEFAULT NULL,
  `TELEFONE1` VARCHAR(15) NULL DEFAULT NULL,
  `TELEFONE2` VARCHAR(15) NULL DEFAULT NULL,
  `TELEFONE3` VARCHAR(15) NULL DEFAULT NULL,
  `OBSERVACAO` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `trab`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab`.`produto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL DEFAULT NULL,
  `PRECOVENDA` DOUBLE NULL DEFAULT NULL,
  `QUANTIDADE` INT NULL DEFAULT NULL,
  `PRECOCOMPRA1` VARCHAR(45) NULL DEFAULT NULL,
  `PRECOCOMPRA2` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trab`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab`.`venda` (
  `id` INT NOT NULL,
  `produto` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
